### ISSUE TITLE
Grid visibility & Axis type and visibility should be sent with Send View

### ISSUE THREAD

**Issue by cbradyatinquire** [MathNetDev/MathNetClient#31] opened 2018-09-21 22:01 UTC

**Comment by ghost** [comment] 2018-09-23 22:47
@cbradyatinquire @tobinwhite I have a question. We have 2 options here:
1) A WYSIWYG approach would involve automatically sending to the clients the settings the admin sets for the axis and grid lines. An API call does exists for getting the current grid visibility so that's possible. However, for the axis, there is no API call which can give us certain settings such as the number of steps/distance set in an applet. Hence we wouldn't be able to send this information automatically to clients.
2) As an alternative if we need the above we can create a separate checkbox and steps textboxes as is currently present in the user customizations tab for graphics 1 and 2 windows.

Lastly if the 2nd approach is still not convenient, we can try and manually parse the XML to set the appropriate settings without the API calls, however this would probably be a little more cumbersome to do.

**Comment by ghost** [comment] 2018-10-18 03:33
@mtstevens @cbradyatinquire @IsaacNPsmash This should be fixed now for all 3 views. Please test and let me know. Thanks.

**Comment by mtstevens** [comment] 2018-10-18 18:14
Tested in Test, 10/18/18, 11:10am PDT. Test successful for both Graphics1 and Graphics2, for all grid types and axis visibility. Test partially successful in 3D Graphics: axis visibility (both 'on' and 'off') was successfully sent; however, the gray xy-plane was always sent no matter what was selected as visible/invisible.

**Comment by ghost** [comment] 2018-10-21 08:35
@mtstevens Good catch. I've fixed this now. Please retest. These kind of issues where we keep missing things will keep coming in the future since we're not really setting the entire xml. I'll try and look into this and see if we can find a better solution to solve this problem entirely. Thanks !

**Comment by mtstevens** [comment] 2018-10-21 18:50
Retested in Test, 10/21/18, 11:45am PDT. Test successful. Axes/Grid visibility seems to work as intended.

**Comment by ghost** [comment] 2018-10-21 20:18
Thanks Michael. Closing this as it's working now.

**Closed as completed by ghost** 2018-10-21 20:18 UTC
Labels: Please Test, Adopted by Kevin
